@baseUrl = http://localhost
@port = 8080

GET {{baseUrl}}:{{port}}/owners
Content-Type: application/json
Cookie: session=eyJsb2dnZWQiOiJ0aWFnb0BjYXJmb3JkLmNvbSJ9.ZvWxHQ.5xsPF_6OAA9ECrppksw7u_RGlnc

###

GET {{baseUrl}}:{{port}}/owners/1
Content-Type: application/json
Cookie: session=eyJsb2dnZWQiOiJ0aWFnb0BjYXJmb3JkLmNvbSJ9.ZvWxHQ.5xsPF_6OAA9ECrppksw7u_RGlnc