@baseUrl = http://localhost
@port = 8080

PUT {{baseUrl}}:{{port}}/cars/update
Content-Type: application/json
Cookie: session=eyJsb2dnZWQiOiJ0aWFnb0BjYXJmb3JkLmNvbSJ9.ZvWxHQ.5xsPF_6OAA9ECrppksw7u_RGlnc

{
    "id": 4,
    "owner_id": 1,
    "color": "blue",
    "model": "sedan"
}

###
